/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Announcement: typeof import('./.vitepress/theme/components/Announcement.vue')['default']
    ArticleMetadata: typeof import('./.vitepress/theme/components/ArticleMetadata.vue')['default']
    CopyRight: typeof import('./.vitepress/theme/components/layout/CopyRight.vue')['default']
    Footer: typeof import('./.vitepress/theme/components/layout/Footer.vue')['default']
    HomeFooter: typeof import('./.vitepress/theme/components/home/HomeFooter.vue')['default']
    HomeUnderline: typeof import('./.vitepress/theme/components/home/HomeUnderline.vue')['default']
    Logo: typeof import('./.vitepress/theme/components/Logo.vue')['default']
    NavLink: typeof import('./.vitepress/theme/components/NavLink.vue')['default']
    NavLinks: typeof import('./.vitepress/theme/components/NavLinks.vue')['default']
    SvgIcon: typeof import('./.vitepress/theme/components/SvgIcon.vue')['default']
    VChip: typeof import('./.vitepress/theme/components/VChip/VChip.vue')['default']
    VEmbed: typeof import('./.vitepress/theme/components/embed/VEmbed.vue')['default']
    VIcon: typeof import('./.vitepress/theme/components/VIcon/VIcon.vue')['default']
  }
}
