/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArticlesList: typeof import('./.vitepress/theme/components/ArticlesList.vue')['default']
    ArticlesListItem: typeof import('./.vitepress/theme/components/ArticlesListItem.vue')['default']
    DateTime: typeof import('./.vitepress/theme/components/DateTime.vue')['default']
    Particles: typeof import('./.vitepress/theme/components/Particles/index.vue')['default']
    Tags: typeof import('./.vitepress/theme/components/Tags.vue')['default']
  }
}
